/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GuessGame.java
 *
 * Created on Apr 4, 2011, 12:39:16 AM
 */

package jsmithwk5ilab;
import java.awt.Color;
import java.util.Random;
/**
 *
 * @author Jon Smith
 */
public class GuessGame extends javax.swing.JFrame {

    /** Creates new form GuessGame */
    public GuessGame() {
        initComponents();
    }



    int intRandom = RandomNumber();
    int intLast;
    int intGuess = 1;
    int intBest = 500;


    public int RandomNumber()
    {
        Random rNumber = new Random();
        int r = rNumber.nextInt(1000);

        while(r<1)
        {
            r = rNumber.nextInt(1000);
        }
        if(r>1000)
        {
            r = RandomNumber();
        }

        return r;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtGuessNumber = new javax.swing.JLabel();
        txtGuess = new javax.swing.JTextField();
        btnGuess = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();
        txtToUser = new javax.swing.JLabel();
        txtTaunt = new javax.swing.JLabel();
        txtBest = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("I have a number between 1 and 1000 can you guess my number?  ");

        txtGuessNumber.setText("Please enter your guess # 1");

        btnGuess.setText("Guess");
        btnGuess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuessActionPerformed(evt);
            }
        });

        btnNew.setText("New Game");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        txtToUser.setText("Guess a Number between 1 and 1000");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGuess, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(txtGuessNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnNew, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtGuess, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                    .addComponent(txtToUser, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                    .addComponent(txtTaunt)
                    .addComponent(txtBest))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(11, 11, 11)
                .addComponent(txtToUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGuessNumber)
                    .addComponent(txtGuess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuess)
                    .addComponent(btnNew))
                .addGap(18, 18, 18)
                .addComponent(txtTaunt)
                .addGap(18, 18, 18)
                .addComponent(txtBest)
                .addContainerGap(142, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuessActionPerformed
        // TODO add your handling code here:
        int n = Integer.parseInt(txtGuess.getText());
        int intThis = 0;
        intGuess++;
        txtGuessNumber.setText("Please enter your guess #" + intGuess + ":");
        txtBest.setText("You must make it in " + (intBest - (intGuess - 1)) + " to beat the high score");
        

        if(n<1)
        {
            txtToUser.setText("Please enter a number higher than 1");
        }
        else if(n>1000)
        {
            txtToUser.setText("Please enter a number less than 1000");
        }
        else
        {
            if(intRandom == n)
            {
                txtToUser.setText("Correct");
                intThis = 0;
                txtGuess.setEditable(false);
                txtGuessNumber.setText("Please press ''New Game'' To play again");
                
                    txtTaunt.setText("You made it in " + (intGuess - 1) + ". Try and make it in Less.");
                    
                    if(intBest == 500)
                    {
                         txtBest.setText("You made it in " + (intGuess - 1) + " This is your first time today try again");
                         intBest = intGuess - 1;
                    }
                    else if(intBest>(intGuess - 1))
                    {
                        txtBest.setText("You beat your high score for today!!! Congradulations new high " + (intGuess - 1));
                        intBest = intGuess - 1;
                    }
                    else if(intBest<(intGuess - 1))
                    {
                        txtBest.setText("Current High score is " + intBest + " Try and Beat that");
                    }
                    else if(intBest == (intGuess - 1))
                    {
                         txtBest.setText("You tied the current high score at " + intBest);
                    }
                    
                    
                

            }
            else if(n>intRandom)
            {
                intThis = n - intRandom;
                txtToUser.setText("Too High");
            }
            else
            {
                intThis = intRandom - n;
                txtToUser.setText("Too Low");
            }

            if(intThis == 0)
            {
                txtToUser.setForeground(Color.black);
            }
            else if(intThis == intLast)
            {
                txtToUser.setForeground(Color.black);
            }
            else if(intThis>intLast)
            {
                txtToUser.setForeground(Color.blue);
            }
            else
            {
                txtToUser.setForeground(Color.red);
            }

            intLast = intThis;


        }

    }//GEN-LAST:event_btnGuessActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        // TODO add your handling code here:
        txtToUser.setText("Guess a number between 1 and 1000");
        txtGuessNumber.setText("Please enter your guess #1");
        intGuess = 1;
        intRandom = RandomNumber();
        txtGuess.setEditable(true);
        txtTaunt.setText("Your current high is: " + intBest);
        txtBest.setText("");
    }//GEN-LAST:event_btnNewActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuessGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuess;
    private javax.swing.JButton btnNew;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel txtBest;
    private javax.swing.JTextField txtGuess;
    private javax.swing.JLabel txtGuessNumber;
    private javax.swing.JLabel txtTaunt;
    private javax.swing.JLabel txtToUser;
    // End of variables declaration//GEN-END:variables

}
