/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Wk1iLabForm.java
 *
 * Created on Mar 7, 2011, 11:58:22 AM
 */

package jsmithwk1ilab;

/**
 *
 * @author Jon Smith
 */
public class Wk1iLabForm extends javax.swing.JFrame {

    /** Creates new form Wk1iLabForm */
    public Wk1iLabForm() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtboxRadius = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDiameter = new javax.swing.JLabel();
        txtCircum = new javax.swing.JLabel();
        txtArea = new javax.swing.JLabel();
        btnCalculate = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtFiveDigits = new javax.swing.JTextField();
        btnFiveDigits = new javax.swing.JButton();
        btnBoth = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtDigits = new javax.swing.JLabel();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Diameter:");

        jLabel2.setText("Circumference:");

        jLabel3.setText("Area:");

        jLabel4.setText("Radius");

        txtDiameter.setText("*****");

        txtCircum.setText("*****");

        txtArea.setText("*****");

        btnCalculate.setText("Click to Calculate");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        jLabel5.setText("Input 5 numbers:");

        btnFiveDigits.setText("Five Digit Operator");
        btnFiveDigits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiveDigitsActionPerformed(evt);
            }
        });

        btnBoth.setText("Click for both");
        btnBoth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBothActionPerformed(evt);
            }
        });

        jLabel6.setText("5 Digits");

        txtDigits.setText("*****");

        btnClear.setText("Click to Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnClear, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                            .addComponent(btnFiveDigits, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                            .addComponent(btnCalculate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                                .addComponent(txtCircum))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                                .addComponent(txtDiameter))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txtboxRadius, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtArea)
                                    .addComponent(txtFiveDigits, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)))
                            .addComponent(txtDigits)
                            .addComponent(btnBoth, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE))
                        .addGap(212, 212, 212))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtboxRadius, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCalculate)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDiameter))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCircum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtArea))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtFiveDigits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnFiveDigits)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtDigits))
                .addGap(18, 18, 18)
                .addComponent(btnBoth)
                .addGap(18, 18, 18)
                .addComponent(btnClear)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        // TODO add your handling code here:
    String firstNumber;     //first dstring entered by the user
    double dblRadius;          //converted user for Radius
    double dblDiameter;        //Finds the Diameter from the Radius
    double dblCircum;          //Finds the Circumference from the Radius
    double dblArea;            //Finds the Area from the Radius
    //read in first number as a string
    dblRadius = Double.parseDouble(txtboxRadius.getText());
    //figures out the Diameter
    dblDiameter = 2*dblRadius;
    //Figures out the Circumference
    dblCircum = 2*Math.PI*dblRadius;
    //Figures out the Area
    dblArea = Math.PI*dblRadius*dblRadius;
    //display the results
    txtDiameter.setText("" + dblDiameter);
    txtCircum.setText("" + dblCircum);
    txtArea.setText("" + dblArea);
    }//GEN-LAST:event_btnCalculateActionPerformed

    private void btnFiveDigitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiveDigitsActionPerformed
        // TODO add your handling code here:
        String secondNumber;
        int q;
        String strNumber = "";

        secondNumber = txtFiveDigits.getText();
        q = Integer.parseInt(secondNumber);
        secondNumber = "" + q;

        char[] DigitArray = secondNumber.toCharArray();
        for(int i = 0; i < DigitArray.length; i++)
        {
            strNumber = strNumber + " " + DigitArray[i];
        }
        txtDigits.setText(strNumber);
    }//GEN-LAST:event_btnFiveDigitsActionPerformed

    private void btnBothActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBothActionPerformed
        // TODO add your handling code here:
        btnFiveDigitsActionPerformed(evt);
        btnCalculateActionPerformed(evt);

    }//GEN-LAST:event_btnBothActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txtFiveDigits.setText("");
        txtboxRadius.setText("");
        txtDigits.setText("*****");
        txtDiameter.setText("*****");
        txtCircum.setText("*****");
        txtArea.setText("*****");
    }//GEN-LAST:event_btnClearActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Wk1iLabForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBoth;
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnFiveDigits;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel txtArea;
    private javax.swing.JLabel txtCircum;
    private javax.swing.JLabel txtDiameter;
    private javax.swing.JLabel txtDigits;
    private javax.swing.JTextField txtFiveDigits;
    private javax.swing.JTextField txtboxRadius;
    // End of variables declaration//GEN-END:variables

}
